### ISSUE TITLE
Firefox Bug

### ISSUE THREAD

**Issue by ui-guys** [Uiseguys/ng-bs-redux-boilerplate#51]
Please open in Firefox:
https://ng-bs-redux-boilerplate.herokuapp.com/

You see the message:
"Stencil app is disabled for this browser."
and much more text complaining something was not built in production mode.

**Comment by AlexanderSergan** [comment]
Fixed. Stencil-bs-ui-lib must be built with --es5 tag. Please check out [PR#53](https://github.com/Uiseguys/ng-bs-redux-boilerplate/pull/53) and update heroku demo.

**Comment by AlexanderSergan** [comment]
Demo updated, closing this issue
